name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧
        run: |
          npm install
          npm run build
        env:
          ARCGIS_API_KEY: ${{ secrets.ARCGIS_API_KEY }}
      - name: Generate screeenshot (optional)
        working-directory: public
        continue-on-error: true
        run: |
          npm install --global pageres-cli
          npm install --global serve
          echo "{\"trailingSlash\":true}" > serve.json
          serve . -p 5000 &
          pageres http://localhost:5000/index.html 1280x1024 --filename=screenshot --delay=10
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: public
